#include "stdafx.h"
#include "GLInfo.h"

const std::map<GLenum, GLenum> GLInfo::BufferBindingMap = 
{
	{ GL_ARRAY_BUFFER,				GL_ARRAY_BUFFER_BINDING					},
	{ GL_ATOMIC_COUNTER_BUFFER,		GL_ATOMIC_COUNTER_BUFFER_BINDING		},
	{ GL_COPY_READ_BUFFER,			GL_COPY_READ_BUFFER_BINDING				},
	{ GL_COPY_WRITE_BUFFER,			GL_COPY_WRITE_BUFFER_BINDING			},
	{ GL_DISPATCH_INDIRECT_BUFFER,	GL_DISPATCH_INDIRECT_BUFFER_BINDING		},
	{ GL_DRAW_INDIRECT_BUFFER,		GL_DRAW_INDIRECT_BUFFER_BINDING			},
	{ GL_ELEMENT_ARRAY_BUFFER,		GL_ELEMENT_ARRAY_BUFFER_BINDING			},
	{ GL_PIXEL_PACK_BUFFER,			GL_PIXEL_PACK_BUFFER_BINDING			},
	{ GL_PIXEL_UNPACK_BUFFER,		GL_PIXEL_UNPACK_BUFFER_BINDING			},
	{ GL_QUERY_BUFFER,				GL_QUERY_BUFFER_BINDING					},
	{ GL_SHADER_STORAGE_BUFFER,		GL_SHADER_STORAGE_BUFFER_BINDING		},
	{ GL_TEXTURE_BUFFER	,			GL_TEXTURE_BUFFER_BINDING				},
	{ GL_TRANSFORM_FEEDBACK_BUFFER,	GL_TRANSFORM_FEEDBACK_BUFFER_BINDING	},
	{ GL_UNIFORM_BUFFER,			GL_UNIFORM_BUFFER_BINDING				}
};